<?php
/*
 * Created by PhpStorm.
 *
 * User: zOmArRD
 * Date: 4/3/2022
 *
 * Copyright © 2022 zOmArRD (omar@ghostlymc.live) - All Rights Reserved.
 */
declare(strict_types=1);

namespace zomarrd\almadeath;

use pocketmine\plugin\PluginBase;

final class AlmaDeath extends PluginBase
{
    public static AlmaDeath $instance;

    public static function getInstance(): AlmaDeath
    {
        return self::$instance;
    }

    public function onLoad(): void
    {
        self::$instance = $this;
    }

    public function onEnable(): void
    {
        // TODO: Change the autogenerated stub
    }

    public function onDisable(): void
    {
        // TODO: Change the autogenerated stub
    }
}